# Generated by Django 3.2.5 on 2021-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210729_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_creat_and_upd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(verbose_name='текст заметки'),
        ),
    ]
